/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartList: typeof import('./../src/views/CartList/index.vue')['default']
    'Category-[id]': typeof import('./../src/views/category/[id].vue')['default']
    Checkout: typeof import('./../src/views/Checkout/index.vue')['default']
    Detail: typeof import('./../src/views/Detail/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    GoodsHot: typeof import('./../src/components/GoodsHot.vue')['default']
    GoodsImage: typeof import('./../src/components/GoodsImage.vue')['default']
    GoodsItem: typeof import('./../src/components/GoodsItem.vue')['default']
    GoodsSku: typeof import('./../src/components/GoodsSku.vue')['default']
    Home: typeof import('./../src/views/Home/index.vue')['default']
    HomeComponentsHomeBanner: typeof import('./../src/views/Home/components/HomeBanner.vue')['default']
    HomeComponentsHomeCategory: typeof import('./../src/views/Home/components/HomeCategory.vue')['default']
    HomeComponentsHomeHot: typeof import('./../src/views/Home/components/HomeHot.vue')['default']
    HomeComponentsHomeNew: typeof import('./../src/views/Home/components/HomeNew.vue')['default']
    HomeComponentsHomePanel: typeof import('./../src/views/Home/components/HomePanel.vue')['default']
    HomeComponentsHomeProduct: typeof import('./../src/views/Home/components/HomeProduct.vue')['default']
    LayoutCart: typeof import('./../src/components/layout/cart.vue')['default']
    LayoutFixed: typeof import('./../src/components/layout/fixed.vue')['default']
    LayoutFooter: typeof import('./../src/components/layout/footer.vue')['default']
    LayoutHeader: typeof import('./../src/components/layout/header.vue')['default']
    LayoutNav: typeof import('./../src/components/layout/nav.vue')['default']
    Login: typeof import('./../src/views/Login/index.vue')['default']
    Member: typeof import('./../src/views/Member/index.vue')['default']
    MemberComponentsUserInfo: typeof import('./../src/views/Member/components/UserInfo.vue')['default']
    MemberComponentsUserOrder: typeof import('./../src/views/Member/components/UserOrder.vue')['default']
    Pay: typeof import('./../src/views/Pay/index.vue')['default']
    PayPayBack: typeof import('./../src/views/Pay/PayBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategory: typeof import('./../src/views/SubCategory/index.vue')['default']
  }
}
