/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '': RouteRecordInfo<'', '/', Record<never, never>, Record<never, never>>,
    'CartList': RouteRecordInfo<'CartList', '/CartList', Record<never, never>, Record<never, never>>,
    'category-[id]': RouteRecordInfo<'category-[id]', '/category/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Checkout': RouteRecordInfo<'Checkout', '/Checkout', Record<never, never>, Record<never, never>>,
    'Detail': RouteRecordInfo<'Detail', '/Detail', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/Home', Record<never, never>, Record<never, never>>,
    'Home-components-HomeBanner': RouteRecordInfo<'Home-components-HomeBanner', '/Home/components/HomeBanner', Record<never, never>, Record<never, never>>,
    'Home-components-HomeCategory': RouteRecordInfo<'Home-components-HomeCategory', '/Home/components/HomeCategory', Record<never, never>, Record<never, never>>,
    'Home-components-HomeHot': RouteRecordInfo<'Home-components-HomeHot', '/Home/components/HomeHot', Record<never, never>, Record<never, never>>,
    'Home-components-HomeNew': RouteRecordInfo<'Home-components-HomeNew', '/Home/components/HomeNew', Record<never, never>, Record<never, never>>,
    'Home-components-HomePanel': RouteRecordInfo<'Home-components-HomePanel', '/Home/components/HomePanel', Record<never, never>, Record<never, never>>,
    'Home-components-HomeProduct': RouteRecordInfo<'Home-components-HomeProduct', '/Home/components/HomeProduct', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/Login', Record<never, never>, Record<never, never>>,
    'Member': RouteRecordInfo<'Member', '/Member', Record<never, never>, Record<never, never>>,
    'Member-components-UserInfo': RouteRecordInfo<'Member-components-UserInfo', '/Member/components/UserInfo', Record<never, never>, Record<never, never>>,
    'Member-components-UserOrder': RouteRecordInfo<'Member-components-UserOrder', '/Member/components/UserOrder', Record<never, never>, Record<never, never>>,
    'Pay': RouteRecordInfo<'Pay', '/Pay', Record<never, never>, Record<never, never>>,
    'Pay-PayBack': RouteRecordInfo<'Pay-PayBack', '/Pay/PayBack', Record<never, never>, Record<never, never>>,
    'SubCategory': RouteRecordInfo<'SubCategory', '/SubCategory', Record<never, never>, Record<never, never>>,
  }
}
